version: "3.9"

services:
  mproc:
    build:
      context: .
      dockerfile: Dockerfile
      target: prerelease
    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: mproc_local
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 3000
      USER_AUTH_ALLOWED_ORIGINS: '["http://localhost:5173", "http://app.mproc.io:5173"]'
      JWT_SECRET: secret
      WEBAUTHN_RP_NAME: Mproc
      WEBAUTHN_RP_ID: localhost
      WEBAUTHN_ORIGIN: http://localhost:5173
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./tests:/usr/src/app/tests
      - ./uploads:/usr/src/app/uploads
    ports:
      - 3000:3000

  postgres_db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
